spring.application.name=pavu-shop

server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#Images
upload.path=upload/image
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Loi 404
server.error.whitelabel.enabled=false
server.error.path=/error

# cau hinh muc do log cho spring seccurity
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# cau hinh duong dan toi file khoa RSA
jwt.rsa-private-key=classpath:certs/privateKey.pem
jwt.rsa-public-key=classpath:certs/publicKey.pem

# cau hinh email-otp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phamduc1022@gmail.com
spring.mail.password=uszi ckqg lfqk wtri
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# cau hinh redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

# cau hinh email admin
shop.admin.email=thangcunbn@gmail.com



